language: android

sudo: false

branches:
  only: master

before_install:
  - yes | sdkmanager "platforms;android-27"

script: ./gradlew :interface:install

android:
  components:
    - build-tools-27.0.3
    - android-27

    - platform-tools
    - tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

env:
  global:
  # try to fix "PermGen space"
  - GRADLE_OPTS="-Xmx256m -XX:MaxPermSize=256m"

after_success:
  # run bintray upload straight after deploy
  - ./gradlew :interface:bintrayUpload